language: python

python:
  - 2.7

# sadly caches only work in travis docker containers (sudo-less)
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
    - /home/travis/virtualenv/python2.7.9/bin

addons:
  postgresql: 9.3

env:
  global:
    - PATH: "$HOME/interlis:$PATH"
    - CI=true
    - DJANGO_DEBUG=true
    - secure: "RC8P0y4q2g8ErB7MnTz4w5q1PK79rYeLN7YHfqaLZ4QeL+FF5cIVw9YP4iCI3I4mq7zm++jSQFoZj75G3iX8VZgJSqJjsriZKi6jXBqkF2q9CUWTJI935sNrRfaTC+Dxgcve5xK7ddIGuCmusN2foYSaon5Zlrq1xSTCcnMjV/M="

install:
  - pip install pybuilder
  - npm install -g npm@latest
  - npm cache clean
  - npm install -g bower grunt-cli
  - npm install -g tsd@next
  # - gem update --system
  # - gem install compass # SASS/SCSS
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - sudo apt-get install gdal-bin libgdal-dev libgdal1h libgdal1-dev # ogr2ogr/GDAL
  - sudo apt-get install libfreetype6 libfreetype6-dev # pre-req matplotlib
  - sudo apt-get install libxml2-dev libxslt-dev python-dev # lxml

before_script:
  - psql -c "CREATE USER opendatahub WITH PASSWORD 'opendatahub';" -U postgres
  - psql -c 'CREATE DATABASE opendatahub;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE opendatahub to opendatahub;' -U postgres
  - psql -c 'ALTER USER opendatahub CREATEDB;' -U postgres

script:
 - pip install -r requirements.txt --download-cache $HOME/.pip-cache
 - pip install -r requirements_dev.txt --download-cache $HOME/.pip-cache
 - pyb -v
 - unset DJANGO_DEBUG
 - pyb -v django_collectstatic

before_deploy:
 - heroku pg:reset DATABASE --confirm opendatahub-hsr-dev
 - git config --global user.email 'build@travis-ci.com'
 - git config --global user.name 'Tavis CI'
 - git add -f $TRAVIS_BUILD_DIR/src/main/webapp/dist $TRAVIS_BUILD_DIR/src/main/staticfiles
 - git commit -q -m 'deploy to heroku'
 - cd $TRAVIS_BUILD_DIR

deploy:
  provider: heroku
  strategy: git
  skip_cleanup: true
  api_key:
    secure: Qb2O3PviVvKvxUxDuxxz8bxbVniNHgBYJxCzDBpLC56d7i5/yiZX9X2sBrFvBhFyh2naidzp0s9EgoN3U2HISaoThzM8/075pIlTnI7dir6R1623ngv7+COXAqoFRNME0A6ghJhTIfxEnDdNrztfQ8WcnVXuNU37kWIHGYryiJk=
  app:
    master: opendatahub-hsr-dev
  run:
    - django-admin makemigrations --pythonpath=/app/src/main/python/ --settings=opendatahub.settings --noinput && django-admin migrate --pythonpath=/app/src/main/python/ --settings=opendatahub.settings --noinput
    - django-admin createcachetable --pythonpath=/app/src/main/python/ --settings=opendatahub.settings
    - django-admin loadfixtures --pythonpath=/app/src/main/python/ --settings=opendatahub.settings

notifications:
  slack:
    on_failure: always
    on_success: change
    rooms:
      - opendatahub:kFUd9okBkUuXn6L66bB9w65f#webapp
