language: python

python:
  - 2.7

addons:
  postgresql: 9.3

install:
  - pip install pybuilder

before_script:
  - psql -c "CREATE USER opendatahub WITH PASSWORD 'opendatahub';" -U postgres
  - psql -c 'create database opendatahub;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE opendatahub to opendatahub;' -U postgres
  - psql -c 'ALTER USER opendatahub CREATEDB;' -U postgres

script:
 - pyb -v
 - cd src/main/webapp/
 - npm install -g bower grunt-cli
 - bower install
 - cd $TRAVIS_BUILD_DIR
 - git add -f .
 - git commit -m 'deploy to heroku'

notifications:
  slack:
    on_failure: always
    on_success: change
    rooms:
      - hsrdat:kFUd9okBkUuXn6L66bB9w65f#webapp

deploy:
  provider: heroku
  strategy: git
  skip_cleanup: true
  api_key:
    secure: Qb2O3PviVvKvxUxDuxxz8bxbVniNHgBYJxCzDBpLC56d7i5/yiZX9X2sBrFvBhFyh2naidzp0s9EgoN3U2HISaoThzM8/075pIlTnI7dir6R1623ngv7+COXAqoFRNME0A6ghJhTIfxEnDdNrztfQ8WcnVXuNU37kWIHGYryiJk=
  app:
    master: opendatahub-hsr-dev
