language: python

python:
  - 2.7

# sadly caches only work in travis docker containers (sudo-less)
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
    - /home/travis/virtualenv/python2.7.9/bin

addons:
  postgresql: 9.3

env:
  global:
    - PATH: "$HOME/interlis:$PATH"
    - CI=true
    - DJANGO_DEBUG=true
    - secure: "RC8P0y4q2g8ErB7MnTz4w5q1PK79rYeLN7YHfqaLZ4QeL+FF5cIVw9YP4iCI3I4mq7zm++jSQFoZj75G3iX8VZgJSqJjsriZKi6jXBqkF2q9CUWTJI935sNrRfaTC+Dxgcve5xK7ddIGuCmusN2foYSaon5Zlrq1xSTCcnMjV/M="

install:
  - pip install pybuilder > /dev/null
  - npm install -g npm@latest  > /dev/null
  - npm cache clean  > /dev/null
  - npm install -g bower grunt-cli  > /dev/null
  - npm install -g tsd@next  > /dev/null
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - sudo apt-get install libfreetype6 libfreetype6-dev > /dev/null # pre-req matplotlib
  - sudo apt-get install libxml2-dev libxslt-dev python-dev > /dev/null # lxml

  # Pre-compiled GDAL 1.11.1 because it takes too long otherwise
  - mkdir -p /home/travis/build/gdal
  - curl -L https://www.dropbox.com/s/qxnl7fftyj80zde/gdal-1.11.1-precise64.tar.gz?dl=1 -s -o - | tar xz -C /home/travis/build/gdal -f -
  - export PATH="/home/travis/build/gdal/bin:$PATH"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/travis/build/gdal/lib"
  - export LIBRARY_PATH="$LIBRARY_PATH:/home/travis/build/gdal/lib"
  - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/travis/build/gdal/pkgconfig"
  - export CPPPATH="$CPPPATH:/home/travis/build/gdal/include"
  - export CPATH="$CPATH:/home/travis/build/gdal/include"

before_script:
  - psql -c "CREATE USER opendatahub WITH PASSWORD 'opendatahub';" -U postgres
  - psql -c 'CREATE DATABASE opendatahub;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE opendatahub to opendatahub;' -U postgres
  - psql -c 'ALTER USER opendatahub CREATEDB;' -U postgres

script:
 - pyb -v
 - unset DJANGO_DEBUG
 - export DJANGO_CONFIG=PRODUCTION
 - pyb -v django_collectstatic

before_deploy:
 - heroku pg:reset DATABASE --confirm opendatahub-hsr-dev
 - git config --global user.email 'build@travis-ci.com'
 - git config --global user.name 'Tavis CI'
 - git add -f $TRAVIS_BUILD_DIR/src/main/webapp/dist $TRAVIS_BUILD_DIR/src/main/staticfiles
 - git commit -q -m 'deploy to heroku'
 - cd $TRAVIS_BUILD_DIR

deploy:
  provider: heroku
  strategy: git
  skip_cleanup: true
  api_key:
    secure: Qb2O3PviVvKvxUxDuxxz8bxbVniNHgBYJxCzDBpLC56d7i5/yiZX9X2sBrFvBhFyh2naidzp0s9EgoN3U2HISaoThzM8/075pIlTnI7dir6R1623ngv7+COXAqoFRNME0A6ghJhTIfxEnDdNrztfQ8WcnVXuNU37kWIHGYryiJk=
  app:
    master: opendatahub-hsr-dev
  run:
    - django-admin makemigrations --pythonpath=/app/src/main/python/ --settings=opendatahub.settings --noinput && django-admin migrate --pythonpath=/app/src/main/python/ --settings=opendatahub.settings --noinput
    - django-admin createcachetable --pythonpath=/app/src/main/python/ --settings=opendatahub.settings
    - django-admin loadfixtures --pythonpath=/app/src/main/python/ --settings=opendatahub.settings

notifications:
  slack:
    on_failure: always
    on_success: change
    rooms:
      - opendatahub:kFUd9okBkUuXn6L66bB9w65f#webapp
